global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['demo-backend:8081']

  - job_name: 'nginx-frontend'
    static_configs:
      - targets: ['nginx-exporter:9113'] # Az exporter portja

  - job_name: 'pg_exporter_v1'
    static_configs:
      - targets: ['pg_exporter:9630']