{
 "title": "Spring Basic Dashboard",
 "description": "Basic dashboard with RAM, CPU and HTTP Request monitoring for myself. Spring Boot Prometheus Actuator endpoint datasource.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "CPU USAGE - JVM Garbage Collector activites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum[5m])) / sum(rate(process_uptime_seconds[5m])) * 100",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "RAM Usage - By Services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum without (id) (jvm_memory_used_bytes)",
     "legendFormat": "{{application}} - {{area}}"
    }
   ]
  },
  {
   "title": "RAM Usage - By Services - HEAP",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (id) (jvm_memory_used_bytes{area=\"heap\"})/sum without (id) (jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "RAM Usage - By Services - NON - HEAP",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (id) (jvm_memory_used_bytes{area=\"nonheap\"})/sum without (id) (jvm_memory_max_bytes{area=\"nonheap\"})",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "{{application}} - {{uri}} - {{method}}-  {{status}}"
    }
   ]
  }
 ]
}